import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

const myFont = localFont({
  src: "./font/BYekan.ttf",
});

export const metadata = {
  title: "بلو بانک",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={myFont.className}>
        <div className="w-full">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
